[package]
name = "post-archiver-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
post-archiver = { path = "../post-archiver" }
axum = "0.8.1"
axum-reverse-proxy = "0.5.1"
mime_guess = "2.0.5"
rusqlite = { version = "0.32.1", features = ["bundled", "chrono"] }
rust-embed = "8.5.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
chrono = "0.4.39"
clap = { version = "4.5.26", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.2", features = ["tracing"] }
